
let inputsearch=document.querySelector(".search-input");let svgsearch=document.querySelector(".svg-search");let svgbookmark=document.querySelector(".svg-bookmark");let listNavLink_1=document.querySelector(".list-nav__link-1");let listNavLink_2=document.querySelector(".list-nav__link-2");let cartSvg=document.querySelector('.cart-svg');function hover(){svgsearch.style.opacity="0.9";}
function nohover(){svgsearch.style.opacity="0.3";}
function fill(){svgsearch.style.fill="#ee3643";}
function whitefill(){svgsearch.style.fill="white";}
inputsearch.onmouseover=function(){hover();inputsearch.onclick=function(){fill();inputsearch.style.backgroundColor="white";};inputsearch.onmouseout=function(){nohover();whitefill();inputsearch.style.backgroundColor="#212a3a";};};listNavLink_1.onmouseover=function(){svgbookmark.style.opacity='0.9';}
listNavLink_1.onmouseout=function(){svgbookmark.style.opacity='0.3';}
listNavLink_2.onmouseover=function(){cartSvg.style.opacity="0.9";}
listNavLink_2.onmouseout=function(){cartSvg.style.opacity='0.3';}
buttonBack=document.querySelector(".list-offers__back");buttonNext=document.querySelector(".list-offers__next");slider1=document.querySelector(".slider-1");slider2=document.querySelector(".slider-2");buttonNext.onclick=function(){slider1.style.display='none';slider2.style.display='flex';}
buttonBack.onclick=function(){slider2.style.display='none';slider1.style.display='flex';}
let servicesWrapper3=document.querySelector(".services__wrapper-3");let servicesWrapper4=document.querySelector(".services__wrapper-4");let servicesWrapper5=document.querySelector(".services__wrapper-5");let button1=document.querySelector(".services__button-1");let button2=document.querySelector(".services__button-2");let button3=document.querySelector(".services__button-3");let service1=document.querySelector(".services__item-1");let service2=document.querySelector(".services__item-2");let service3=document.querySelector(".services__item-3");let span1=document.querySelector(".services__span-1");let span2=document.querySelector(".services__span-2");let span3=document.querySelector(".services__span-3");button1.onclick=function(){servicesWrapper3.style.display='flex';servicesWrapper4.style.display='none';servicesWrapper5.style.display='none';service1.classList.add("services__item-active");service2.classList.remove("services__item-active");service3.classList.remove("services__item-active");span1.classList.add("span-active");span2.classList.remove("span-active");span3.classList.remove("span-active");}
button2.onclick=function(){servicesWrapper3.style.display='none';servicesWrapper4.style.display='flex';servicesWrapper5.style.display='none';service2.classList.add("services__item-active");service1.classList.remove("services__item-active");service3.classList.remove("services__item-active");span2.classList.add("span-active");span1.classList.remove("span-active");span3.classList.remove("span-active");}
button3.onclick=function(){servicesWrapper5.style.display='flex';servicesWrapper3.style.display='none';servicesWrapper4.style.display='none';service1.classList.remove("services__item-active");service2.classList.remove("services__item-active");service3.classList.add("services__item-active");span3.classList.add("span-active");span2.classList.remove("span-active");span1.classList.remove("span-active");}